pipeline {
    agent any
    stages() {
        stage("git pull"){
            steps{
                git branch: "main", url: "https://github.com/piyushnandu1996/DEVOPS-PIPELINE-PROJECTS.git"
            }
        }
        
        stage("Installing packages"){
            steps{
                sh '''
                    if ! node -v 2>/dev/null ;
                    then
                        sudo apt install -y nodejs npm
                        sudo npm install pm2 -g
                    fi
                    '''
            }
        }
        
        stage("Building project with npm"){
            steps{
                dir('javascript-build-with-nodejs/project/DEMO/backend'){
                    sh ''' 
                        sudo rm -rf node_modules package-lock.json
                        npm cache clean --force 
                        npm install --no-audit --no-fund
                        if command sudo pm2 status | grep server  ; 
                            then sudo pm2 stop server
                        fi
                        '''
                }
            }
        }
        
        stage('starting backend'){
            steps{
                dir('javascript-build-with-nodejs/project/DEMO/backend'){
                sh 'sudo pm2 start server.js'
                }
            }
        }
        
        
    }
}
